Repository Company-Pawkeeprs/landing-page, pull requests merged in 2024-06, with the labels that each got.

#22 refactor: alterando textos e excluindo seções da landing page
  source/pages/Home/HomePage.tsx
  source/pages/Home/business-differentials.tsx
  source/pages/Home/problems-faced-by-beginners.tsx
  source/pages/Home/problems-faced-by-veterinarians.tsx
  source/pages/Home/solutions.tsx
Labels: refactor

#23 fix: correções nas chamadas de links e efeito em botões.
  pages/tutor/index.tsx
  pages/veterinary/index.tsx
  source/Components/molecules/nav-bar-home/index.tsx
  source/Components/molecules/nav-bar-landing/index.tsx
  source/Layouts/Header.tsx
  source/pages/Home/HomePage.tsx
Labels: fix

#24 refactor: atualiza links e estilos do componente NavbarHome.
  source/Components/molecules/nav-bar-home/index.tsx
  source/pages/Home/HomePage.tsx
Labels: refactor

#17 style: ajustes na responsividade na sessão do roadmap e pricing
  source/Components/molecules/pricing-card/index.tsx
  source/Components/molecules/text-image-pattern/image.tsx
  source/Components/molecules/text-image-pattern/index.tsx
  source/Components/molecules/text-image-pattern/text.tsx
  source/pages/Home/HomePage.tsx
  source/pages/Home/business-roadmap.tsx
  source/pages/Home/reasons-to-use.tsx
Labels: fix

#39 refactor: alterando o layout da landing page
  public/home/icon-checked.png
  public/home/icon1.png
  public/home/icon2.png
  public/home/icon3.png
  public/home/icon4.png
  public/home/ilustracao1.png
  public/home/ilustracao2.png
  public/home/ilustracao4.png
  public/home/ilustracao5.png
  source/Components/molecules/nav-bar-home/index.tsx
  source/pages/Home/HomePage.tsx
Labels: refactor

#40 feat: sessão de planos e adição de tagkeepr.
  public/home/icon1-yellow.png
  public/home/icon5.png
  public/home/icon6.png
  public/home/icon7.png
  public/home/ilustracao1.png
  public/home/ilustracao3.png
  public/home/ilustracao4.png
  public/home/ilustracao6.png
  public/home/tagkeepr.jpeg
  public/home/tagkeepr.jpeg:Zone.Identifier
  source/Components/molecules/nav-bar-home/index.tsx
  source/Components/molecules/pricing-card/index.tsx
  source/pages/Home/HomePage.tsx
Labels: refactor

#55 refactor: atualizando textos, valores e responsividade
  public/home/icon10.png
  public/home/icon3-green.png
  public/home/icon4-green.png
  public/home/icon8.png
  public/home/icon9.png
  source/Components/molecules/pricing-card/index.tsx
  source/pages/Home/HomePage.tsx
Labels: refactor

#56 refactor: remove código desnecessário.
  package.json
  pages/404.tsx
  pages/500.tsx
  source/aws.ts
  source/config.ts
  source/reportWebVitals.ts
  yarn.lock
Labels: enhancement
